### ISSUE TITLE
psarc extraction bug

### ISSUE THREAD

**Issue by modusc896d352** [Ekey/U4.PSARC.Tool#1]
tried to extract sound1.psarc and this is what i get

```
UNCHARTED: Legacy of Thieves Collection PSARC Unpacker
(c) 2022 Ekey (h4x0r) / v0.0.1.29415

[UNPACKING]: NamesLookUp.txt

Exceção Sem Tratamento: System.ArgumentException: Já foi adicionado um item com a mesma chave.
   em System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   em System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   em U4.Unpacker.PsarHashList.iLoadNames(Byte[] lpBuffer)
   em U4.Unpacker.PsarcUnpack.iDoIt(String m_Archive, String m_DstFolder)
   em U4.Unpacker.Program.Main(String[] args)
```

i also get this error when extracting english.psarc

```
UNCHARTED: Legacy of Thieves Collection PSARC Unpacker
(c) 2022 Ekey (h4x0r) / v0.0.1.29415


Exceção Sem Tratamento: System.Exception: [ERROR]: Invalid compression type of PSAR archive file!
   em U4.Unpacker.PsarcUnpack.iDoIt(String m_Archive, String m_DstFolder)
   em U4.Unpacker.Program.Main(String[] args)

```

**Comment by Ekey** [comment]
Unfortunately, I don't have a game, I tested code on small files that a friend sent me like this ones :

flash1.psarc
iggy1.psarc
text2.psarc

Probably english.psarc has another compression method. Can you upload sound1.psarc and english.psarc files?

**Comment by modusc896d352** [comment]
oh yeah. will do. ETA for this one will be 30 minutes, give or take.

**Comment by modusc896d352** [comment]
here they are.
[sound1.psarc.7z](https://1fichier.com/?r0i64ao0fzqep5x01zb5)
[english.psarc.7z](https://1fichier.com/?lro70bpxr5ic51prme98)

uploading these files alone took longer than i expected. apologies for my poor choice of filehoster.

**Comment by barnett2010** [comment]
I ran into the same problem, some files could not be unpacked.
You can download the game files here.
magnet:?xt=urn:btih:8111D8171173632BC20313D55E097A77FA02F773 ​​​​

**Comment by barnett2010** [comment]
rad1.psarc and texturedict2.exe can't unpacked

**Comment by barnett2010** [comment]
After unpacking 。
There are a lot of pak files inside.
should be models 。
should need to be unpacked again。
to open with 3d software.

**Comment by Ekey** [comment]
I just updated the tool, can you check it again?

**Comment by modusc896d352** [comment]
will do.

**Comment by Ekey** [comment]
Updated again to 30910 build.

**Comment by Datura123** [comment]
Hi Ekey! It's work it for Unpacking. Thanks to make it work.

And can you make for the Import tool? Appreciate this!

**Comment by Ekey** [comment]
Unfortunately, I don't have a game to test repacked files and i can't buy cuz it's blocked in my country.

**Comment by modusc896d352** [comment]
yikes
i'll try to help you with the best of my ability.

i extracted english.psarc (from **Uncharted4_data\build\pc\main\sound1\streams\speech** folder) with your 30910 build and your tool successfully extracted every file from there.
i'm currently using the same build to extract sound.1psarc (from **Uncharted4_data\build\pc\main** folder), it's currently extracting all files (not as fast as i expected due to my slow external HDD). but no issues so far.
